/* Parses C style strings
 * Auto generated by generate_fsm.py. Please do not edit.
 */

#define STRINGPARSER_NUM_STATES 4

enum stringparser_state_internal_enum {
  STRINGPARSER_STATE_INT_TEXT,
  STRINGPARSER_STATE_INT_STRING,
  STRINGPARSER_STATE_INT_STRING_ESCAPE
};

static const int stringparser_states_external[] = {
  STRINGPARSER_STATE_TEXT,
  STRINGPARSER_STATE_STRING,
  STRINGPARSER_STATE_STRING
};

static const char * stringparser_states_internal_names[] = {
  "text",
  "string",
  "string_escape"
};

static const struct statetable_transitions_s stringparser_state_transitions[] = {
  { "[:default:]", STRINGPARSER_STATE_INT_STRING_ESCAPE, STRINGPARSER_STATE_INT_STRING },
  { "[:default:]", STRINGPARSER_STATE_INT_STRING, STRINGPARSER_STATE_INT_STRING },
  { "\"", STRINGPARSER_STATE_INT_STRING, STRINGPARSER_STATE_INT_TEXT },
  { "\\", STRINGPARSER_STATE_INT_STRING, STRINGPARSER_STATE_INT_STRING_ESCAPE },
  { "[:default:]", STRINGPARSER_STATE_INT_TEXT, STRINGPARSER_STATE_INT_TEXT },
  { "\"", STRINGPARSER_STATE_INT_TEXT, STRINGPARSER_STATE_INT_STRING },
  { NULL, STATEMACHINE_ERROR, STATEMACHINE_ERROR }
};
